<a href="https://colab.research.google.com/github/tapader13/python-practice-for-academy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
#tuples
a1=np.array((1,2,3))
print(a1)

#list
a2=np.array([1,2,3])
print(a2)

#dimensonal
#0
a3=np.array(1)
print(a3,a3.ndim)

#1
a4=np.array([1,2,3])
print(a4,a4.ndim)

#2
a5=np.array([[1,2,3],[4,5,6]])
print(a5,a5.ndim)

#3
a6=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a6,a6.ndim)

#0 initalize
a7 = np.zeros([3,4])
print(a7, a7.ndim,type(a7))

#1 initalize
a8 = np.ones([3,4])
print(a8, a8.ndim,type(a8))

#specific value initialize
a9=np.full((3,5),9)
print(np.full(3,8))
print(a9,a9.ndim)

#identity matrix
a10=np.eye(3,dtype=int)
print(a10,a10.ndim)

#diagonal value
a11=np.diag([3,4,5])
print(a11, a11.ndim)

#random value
a12=np.random.rand(2,3)
print(a12,type(a12),a12.ndim)
a13 =np.random.randint(1,3,(2,4))
# a13 =np.random.randint(1,3,(2,3,4)) for 3d list
print(a13,type(a13),a13.ndim)


[8 8 8]


In [34]:
#matrix
import numpy as np
a1=np.matrix([[1,2],[3,4]])
print(a1,type(a1))
dit=np.linalg.det(a1)
print(dit)
inverse=np.linalg.inv(a1)
print(inverse)
check_validity=np.dot(a1,inverse)
print(np.round(check_validity,2).astype(int))

[[1 2]
 [3 4]] <class 'numpy.matrix'>
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 0]
 [0 1]]


In [ ]:
import numpy as np
#shape
a1=np.array([1,2,3])
print(a1.shape)
a2=np.array([[1,2,3],[4,5,6]])
print(a2.shape)
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3.shape)

#reshape
a4=np.array([1,2,3,4,5,6])
print(a4.reshape(3,2))
a5=np.array([[1,2,3],[4,5,6]])
print(a5.reshape(3,2))
print(a5.reshape(1,-1))
print(a5.reshape(-1))

#for in loop in array
#1d
a6=np.array([1,2,3,4,5,6])
for i in a6:
    print(i)

#2d
a7=np.array([[1,2,3],[4,5,6]])
for row in a7:
   for col in row:
      print(col,end=" ")
   print()

for row in range(len(a7)):
   for col in range(len(a7[0])):
      print(a7[row][col],end=" ")
   print()
#3d
a8=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in a8:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()

for x in range(len(a8)):
    for y in range(len(a8[0])):
        for z in range(len(a8[0][0])):
            print(a8[x][y][z])

for val in np.nditer(a8):
    print(val)

for x in range(a8.shape[0]):
    for y in range(a8.shape[1]):
        for z in range(a8.shape[2]):
            print(a8[x][y][z])

1 2 3 
4 5 6 

7 8 9 
10 11 12 

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#join
a1=np.array([1,2,3])
a2=np.array([4,5,6])
# a3=np.concatenate((a1,a2))
a3=np.concatenate([a1,a2])
print(a3)

#stack
a4=np.stack((a1,a2))
print(a4)
a5=np.stack([a1,a2],axis=1)
print(a5)
a6=np.vstack([a1,a2])
print(a6)
a7=np.hstack([a1,a2])
print(a7)
d1=np.array([[1,2,3],[4,5,6]])
d2=np.array([[7,8,9],[10,11,12]])
a8=np.dstack([d1,d2])
print(a8)
a9=np.column_stack([a1,a2])
print(a9)

#for 2d, column_stack reamin 2d just increase column but in stack with axis 1 add 1 dim become 3d
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])

print(np.column_stack([b1,b2]))
# Output shape: (2,4) → just columns concatenated

print(np.stack([b1,b2], axis=1))
# Output shape: (2,2,2) → new axis added

#split
a10=np.array([1,2,3,4,5,6])
# a11=np.array_split(a10,3)
# a11=np.array_split(a10,5)
a11=np.split(a10,2)
print(a11)
print(a11[0])

# axis=0 → splits along rows if devided then work otherwise error
# axis=1 → splits along columns

a12=np.array([[1,2,3],[4,5,6]])
# a13=np.split(a12,2)
# a13=np.split(a12,4) error cause 4 is not devided to row 2
a13=np.array_split(a12,3)
print(a13)
print(a13[0])

a14=np.array([[1,2,3],[4,5,6],[7,8,9]])
a15=np.array_split(a14,4) # first res=row//number then rem=row%number then all res+rem row
print(a15)
print(a15[0])


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([], shape=(0, 3), dtype=int64)]
[[1 2 3]]


In [ ]:
#data type
a1=np.array([1,2,3])
print(a1.dtype)
a2=np.array([1.1,2.2,3.3])
print(a2.dtype)
a3=np.array(["minhaj","miftah","mizan","marzan"])
print(a3.dtype)
a4=np.array([True,False,True])
print(a4.dtype)
a5=np.array([1+2j,2+3j,3+4j])
print(a5.dtype)
a6=np.array([1,2,"mnihaj",True])
print(a6.dtype) #U cause numpy need 1 datatype so it upcasting

#manually set up datatype
a7=np.array([1,2,3],dtype=float)
print(a7,a7.dtype)
a8=np.array([1,2,3],dtype=str)
print(a8,a8.dtype)
a9=np.array([1,2,3],dtype=complex)
print(a9,a9.dtype)
a10=np.array([1,2,3],dtype=bool)
print(a10,a10.dtype)
a11=np.array(["1","2","3"],dtype=int)
print(a11,a11.dtype)


#convert list
a12=np.array([1,2,3])
print(a12,a12.dtype)
a13=a12.astype(float)
print(a13,a13.dtype)
a14=a12.astype(str)
print(a14,a14.dtype)

['1' '2' '3'] <U21


In [5]:
#array access
a1=np.array([1,2,3])
print(a1[0])
print(a1[-1])
a2=np.array([[1,2,3],[4,5,6]])
print(a2[0,0])
print(a2[0,-1])
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3[0,0,0])
print(a3[0,1,-1])

1
3
1
3
1
6


In [10]:
#search
import numpy as np
a1=np.array([1,2,3,4,5,4,4])
print(np.where(a1==4))
print(np.where(a1%2==0))

#sort
print(np.sort(a1))
a2=np.array([[3,7,1],[6,2,4]])
print(np.sort(a2))

#min-max
print(np.min(a1))
print(np.max(a1))
print(np.argmax(a1))
print(np.argmin(a1))
print(np.argsort(a1))

print(np.min(a2,axis=0)) #vertilcal min
print(np.max(a2,axis=0))
print(np.argmax(a2,axis=0))


print(np.min(a2,axis=1)) #horizontal min
print(np.max(a2,axis=1))
print(np.argmax(a2,axis=1)) #retrun index of horizontal max


[1 2]


In [22]:
#intersection
a1=np.array([1,2,3,4,5])
a2=np.array([3,4,5,6,7])
print(a1.size)
print(np.intersect1d(a1,a2))

a3=np.array([[1,3,2],[4,5,6]])
a4=np.array([[3,4,5],[7,6,8]])
print(a3.size)
print(a3.T)
print(a3.transpose())
print(np.intersect1d(a3,a4)) #intersection always give sorted result

print(np.union1d(a3,a4))

print(np.setdiff1d(a1,a2))

print(np.sum([a1,a2]))
print(np.sum([a1,a2],axis=0))
print(np.sum([a1,a2],axis=1))

print(np.subtract(a1,a2))
print(np.multiply(a1,a2))
print(np.divide(a1,a2))


print(np.sum([a3,a4]))
print(np.sum([a3,a4],axis=0))
print(np.sum([a3,a4],axis=1))

print(np.subtract(a3,a4))
print(np.multiply(a3,a4))
print(np.divide(a3,a4))

[[1 4]
 [3 5]
 [2 6]]
[[1 4]
 [3 5]
 [2 6]]


In [ ]:
#scaller operation
import numpy as np
a1=np.array([1,2,3])
print(a1*2)
print(a1/2)
print(a1+2)
print(a1-2)

#statistical operation
a2=np.array([1,2,3,4,5])
print(np.mean(a2))
print(np.median(a2))
print(np.std(a2))
print(np.var(a2))
print(np.sqrt(np.var(a2)))

#random in numpy
r1=np.random.randint(5)
print(r1)
r2=np.random.randint(5,size=(2,2))
print(r2)
r3=np.random.choice([1,2,3,4])
print(r3)

#log
arr1=np.array([1,2,3,4,5])
print(np.log2(arr1))
print(np.log10(arr1))

#lcm & gcd/hcm
print(np.lcm(4,8))
print(np.gcd(4,8))

[2 4 6]
[0.5 1.  1.5]
[3 4 5]
[-1  0  1]
3.0
3.0
1.4142135623730951
2.0
1.4142135623730951
2
[[1 0]
 [4 3]]
1
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
8
4


In [6]:
#array slice
a1=np.array([1,2,3,4,5])
print(a1[2:4])
print(a1[:4])
print(a1[2:]) #till last
print(a1[2::2]) #after evert 2 step

a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2[0,1:4])
print(a2[0:2,1:4])

a3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(a3[0,1,2:])
print(a3[0,0:2,2:])
print(a3[0:2,0:2,2:])

[3 4]
[1 2 3 4]
[3 4 5]
[3 5]
[2 3 4]
[[2 3 4]
 [7 8 9]]
[6]
[[3]
 [6]]
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]]
