<a href="https://colab.research.google.com/github/tapader13/python-practice-for-academy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#tuples
a1=np.array((1,2,3))
print(a1)

#list
a2=np.array([1,2,3])
print(a2)

#dimensonal
#0
a3=np.array(1)
print(a3,a3.ndim)

#1
a4=np.array([1,2,3])
print(a4,a4.ndim)

#2
a5=np.array([[1,2,3],[4,5,6]])
print(a5,a5.ndim)

#3
a6=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a6,a6.ndim)

#0 initalize
a7 = np.zeros([3,4])
print(a7, a7.ndim,type(a7))

#1 initalize
a8 = np.ones([3,4])
print(a8, a8.ndim,type(a8))

#specific value initialize
a9=np.full((3,5),9)
print(a9,a9.ndim)

#identity matrix
a10=np.eye(3)
print(a10,a10.ndim)

#diagonal value
a11=np.diag([3,4,5])
print(a11, a11.ndim)

#random value
a12=np.random.rand(2,3)
print(a12,type(a12),a12.ndim)
a13 =np.random.randint(1,3,(2,4))
# a13 =np.random.randint(1,3,(2,3,4)) for 3d list
print(a13,type(a13),a13.ndim)


[[[1 2 2 2]
  [1 2 2 1]
  [1 1 2 1]]

 [[1 1 1 1]
  [2 2 1 2]
  [1 2 2 2]]] <class 'numpy.ndarray'> 3


In [27]:
#data type
a1=np.array([1,2,3])
print(a1.dtype)
a2=np.array([1.1,2.2,3.3])
print(a2.dtype)
a3=np.array(["minhaj","miftah","mizan","marzan"])
print(a3.dtype)
a4=np.array([True,False,True])
print(a4.dtype)
a5=np.array([1+2j,2+3j,3+4j])
print(a5.dtype)
a6=np.array([1,2,"mnihaj",True])
print(a6.dtype) #U cause numpy need 1 datatype so it upcasting

#manually set up datatype
a7=np.array([1,2,3],dtype=float)
print(a7,a7.dtype)
a8=np.array([1,2,3],dtype=str)
print(a8,a8.dtype)
a9=np.array([1,2,3],dtype=complex)
print(a9,a9.dtype)
a10=np.array([1,2,3],dtype=bool)
print(a10,a10.dtype)
a11=np.array(["1","2","3"],dtype=int)
print(a11,a11.dtype)


#convert list
a12=np.array([1,2,3])
print(a12,a12.dtype)
a13=a12.astype(float)
print(a13,a13.dtype)
a14=a12.astype(str)
print(a14,a14.dtype)

['1' '2' '3'] <U21


In [34]:
#array access
a1=np.array([1,2,3])
print(a1[0])
print(a1[-1])
a2=np.array([[1,2,3],[4,5,6]])
print(a2[0,0])
print(a2[0,-1])
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3[0,0,0])
print(a3[0,1,-1])

1
3
1
3
1
6


In [44]:
#array slice
a1=np.array([1,2,3,4,5])
print(a1[2:4])
print(a1[:4])
print(a1[2:]) #till last
print(a1[2::2]) #after evert 2 step

a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2[0,1:4])
print(a2[0:2,1:4])

a3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(a3[0,1,2:])
print(a3[0,0:2,2:])
print(a3[0:2,0:2,2:])

[3 4]
[1 2 3 4]
[3 4 5]
[3 5]
[2 3 4]
[[2 3 4]
 [7 8 9]]
[6]
[[3]
 [6]]
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]]
